resources:
  - name: dwGitRepo
    type: GitRepo
    configuration:
      gitProvider: davidw
      path: david-jfrog/demo
      branches:
        include: main
  - name: dwBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryUnified
      buildName: SampleApp
      buildNumber: 1
pipelines:
  - name: dw_basic_pipeline
    configuration:
      environmentVariables:
        readOnly:
          dw_env_var: "hello"
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: dwGitRepo
          outputResources:
            - name: dwBuildInfo
        execution:
          onExecute:
            - echo $dw_env_var
            - if [ -z $app_version ]; then add_pipeline_variables app_version=1.0.0; else app_version=$(bump_semver $app_version minor); fi
            - write_output dwBuildInfo "buildNumber=$app_version"
            - add_run_variables run_var="hello"
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: dwBuildInfo
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: ['11']
        execution:
          onExecute:
            - echo $run_var
            - echo $res_dwBuildInfo_buildNumber

      - name: step_3
        type: Bash
        configuration:
          environmentVariables:
            step_env_var1: "hello"
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo $step_env_var1

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo $app_version
      - name: step_5
        type: Bash
        configuration:
          inputSteps:
            - name: step_3
            - name: step_4
          integrations:
            - name: Github_SolEng
        execution:
          onExecute:
            - 'curl -H "Authorization: token ${int_dw_github_token}" ${int_dw_github_url}/rate_limit'
